# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# The values specified here will be passed in as environment variables
# to your application. Note that the following environment variables are
# automatically set for you by the environment:
# - GATEWAY_PORT (set to service.internalPort)
# - GATEWAY_NAMESPACE (set to the app's Kubernetes namespace)
# - GATEWAY_NAMED (set to the name of this app)
# - GATEWAY_IP (set to the IP of the pod)
env:
  - name: EXAMPLE
    value: "hello world"

# REQUIRED: your project ID
project: brigade-209a40dd897883b213e679b375a46baa70e102aeba79da69a68e53

replicaCount: 1
image:
  repository: nginx
  tag: stable
  pullPolicy: IfNotPresent
service:
  name: nginx
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
ingress:
  enabled: true
  # Used to create an Ingress record.
  hosts:
    - brigly.technosophos.me
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  tls:
    # Secrets must be manually created in the namespace.
    - secretName: brigly-tls
      hosts:
      - brigly.technosophos.me
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
